#!/usr/bin/env bash
set -Eeuo pipefail

ROOT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
TOOLS_DIR="${ROOT_DIR}/.tools"
STATE_DIR="${TOOLS_DIR}/state"

KICAD_HAPPY_REPO="${KICAD_HAPPY_REPO:-https://github.com/napoleondynamit-e/kikcad-happy.git}"
KICAD_HAPPY_REF="${KICAD_HAPPY_REF:-main}"
DATASHEET_CLI_REPO="${DATASHEET_CLI_REPO:-https://github.com/napoleondynamit-e/datasheet-cli.git}"
DATASHEET_CLI_REF="${DATASHEET_CLI_REF:-master}"

KICAD_HAPPY_DIR="${TOOLS_DIR}/kicad-happy"
DATASHEET_CLI_DIR="${TOOLS_DIR}/src/datasheet-cli"
CHECK_ONLY=false

usage() {
  cat <<'EOF'
Usage: ./bootstrap.sh [--check]

Without arguments, installs or updates project-local tools and links the
kicad-happy skills into .agents/skills.

Options:
  --check    Verify prerequisites and the local installation without changing it.
  -h, --help Show this help.

Repository URLs and branches can be overridden with KICAD_HAPPY_REPO,
KICAD_HAPPY_REF, DATASHEET_CLI_REPO, and DATASHEET_CLI_REF.
EOF
}

log() {
  printf '[bootstrap] %s\n' "$*"
}

die() {
  printf '[bootstrap] ERROR: %s\n' "$*" >&2
  exit 1
}

require_command() {
  command -v "$1" >/dev/null 2>&1 || die "Required command not found: $1"
}

check_prerequisites() {
  require_command git
  require_command cargo
  require_command rustc
  require_command python3
  require_command kicad-cli

  if ! command -v codex >/dev/null 2>&1 \
    && ! command -v cursor-agent >/dev/null 2>&1 \
    && ! command -v cursor >/dev/null 2>&1; then
    log "WARNING: no supported AI agent command found (codex or Cursor)."
  fi
}

sync_repo() {
  local repo="$1"
  local ref="$2"
  local destination="$3"

  if [[ -d "${destination}/.git" ]]; then
    local actual_repo
    actual_repo="$(git -C "${destination}" remote get-url origin)"
    [[ "${actual_repo}" == "${repo}" ]] \
      || die "${destination} uses ${actual_repo}, expected ${repo}"
    [[ -z "$(git -C "${destination}" status --porcelain)" ]] \
      || die "Tool checkout has local changes: ${destination}"

    log "Updating ${destination#"${ROOT_DIR}/"} (${ref})"
    git -C "${destination}" fetch --prune origin
    git -C "${destination}" checkout --quiet "${ref}"
    git -C "${destination}" pull --ff-only origin "${ref}"
    return
  fi

  [[ ! -e "${destination}" ]] \
    || die "Path exists but is not a Git checkout: ${destination}"

  log "Cloning ${repo} (${ref})"
  mkdir -p "$(dirname -- "${destination}")"
  git clone --branch "${ref}" --single-branch "${repo}" "${destination}"
}

link_kicad_happy_skills() {
  local skills_root="${ROOT_DIR}/.agents/skills"
  local manifest="${STATE_DIR}/kicad-happy-skills"
  local new_manifest="${manifest}.new"
  local skill_dir skill_name destination

  mkdir -p "${skills_root}" "${STATE_DIR}"
  : >"${new_manifest}"

  for skill_dir in "${KICAD_HAPPY_DIR}"/skills/*; do
    [[ -f "${skill_dir}/SKILL.md" ]] || continue
    skill_name="$(basename -- "${skill_dir}")"
    destination="${skills_root}/${skill_name}"

    if [[ -e "${destination}" && ! -L "${destination}" ]]; then
      die "Skill name collision at ${destination}"
    fi

    ln -sfn "../../.tools/kicad-happy/skills/${skill_name}" "${destination}"
    printf '%s\n' "${skill_name}" >>"${new_manifest}"
  done

  if [[ -f "${manifest}" ]]; then
    while IFS= read -r skill_name; do
      [[ -n "${skill_name}" ]] || continue
      if ! grep -Fxq "${skill_name}" "${new_manifest}" \
        && [[ -L "${skills_root}/${skill_name}" ]]; then
        rm "${skills_root}/${skill_name}"
      fi
    done <"${manifest}"
  fi

  mv "${new_manifest}" "${manifest}"
  log "Linked $(wc -l <"${manifest}") kicad-happy skills into .agents/skills"
}

install_datasheet_cli() {
  local commit stamp
  commit="$(git -C "${DATASHEET_CLI_DIR}" rev-parse HEAD)"
  stamp="${STATE_DIR}/datasheet-cli.commit"

  if [[ -x "${TOOLS_DIR}/bin/datasheet" ]] \
    && [[ -f "${stamp}" ]] \
    && [[ "$(<"${stamp}")" == "${commit}" ]]; then
    log "datasheet-cli is already current"
    return
  fi

  log "Building datasheet-cli ${commit:0:12}"
  cargo install \
    --path "${DATASHEET_CLI_DIR}/apps/datasheet-cli" \
    --root "${TOOLS_DIR}" \
    --locked \
    --force
  printf '%s\n' "${commit}" >"${stamp}"
}

write_environment() {
  cat >"${TOOLS_DIR}/env" <<EOF
# Generated by bootstrap.sh. Source this file in an interactive shell.
export PATH="${TOOLS_DIR}/bin:\${PATH}"
export KICAD_HAPPY_DIR="${KICAD_HAPPY_DIR}"
EOF
}

check_local_installation() {
  local failed=false

  [[ -d "${KICAD_HAPPY_DIR}/.git" ]] \
    || { log "MISSING: ${KICAD_HAPPY_DIR}"; failed=true; }
  [[ -x "${TOOLS_DIR}/bin/datasheet" ]] \
    || { log "MISSING: ${TOOLS_DIR}/bin/datasheet"; failed=true; }
  [[ -f "${TOOLS_DIR}/env" ]] \
    || { log "MISSING: ${TOOLS_DIR}/env"; failed=true; }

  if [[ -d "${KICAD_HAPPY_DIR}/skills" ]]; then
    local skill_dir skill_name
    for skill_dir in "${KICAD_HAPPY_DIR}"/skills/*; do
      [[ -f "${skill_dir}/SKILL.md" ]] || continue
      skill_name="$(basename -- "${skill_dir}")"
      [[ -L "${ROOT_DIR}/.agents/skills/${skill_name}" ]] \
        || { log "MISSING skill link: ${skill_name}"; failed=true; }
    done
  fi

  [[ "${failed}" == false ]] || exit 1
  log "Local tool installation is ready"
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --check)
      CHECK_ONLY=true
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      usage >&2
      die "Unknown argument: $1"
      ;;
  esac
  shift
done

check_prerequisites

if [[ "${CHECK_ONLY}" == true ]]; then
  check_local_installation
  exit 0
fi

mkdir -p "${TOOLS_DIR}" "${STATE_DIR}"
sync_repo "${KICAD_HAPPY_REPO}" "${KICAD_HAPPY_REF}" "${KICAD_HAPPY_DIR}"
link_kicad_happy_skills
sync_repo "${DATASHEET_CLI_REPO}" "${DATASHEET_CLI_REF}" "${DATASHEET_CLI_DIR}"
install_datasheet_cli
write_environment
check_local_installation

log "Done. Run: source .tools/env"
